#pragma config(Sensor, port9,  light,          sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port10, color,          sensorVexIQ_ColorHue)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motor2,          pickMotor1,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          pickMotor2,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          rightMortor,   tmotorVexIQ, PIDControl, driveRight, encoder)
#pragma config(Motor,  motor7,          armMotor,      tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor12,         switchMotor,   tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//*****************Author:stefan  mail:stefan1992@qq.com******************************

int flag=0;
int flag2=1;
int e=0;
int c,d;
int pickspeed=0;
int speed=100;

void pick()
{
	c=SensorValue(color);
	d=getColorProximity(color);

	if(vexRT[BtnFUp]||vexRT[BtnFDown])
	{
		pickspeed=0;
		flag2=0;
	}
	else if(vexRT[BtnRDown])
	{
		motor[pickMotor1]=-80;
		motor[pickMotor2]=-80;
		wait1Msec(200);
		pickspeed=speed;
		flag2=1;
	}
	else if(vexRT[BtnRUp])
	{
		pickspeed=speed;
		flag2=1;
	}
	else if(flag==1||flag==2||flag==3)
	{
		if(getMotorZeroPosition(switchMotor)==0)
		{
			pickspeed=0;
		}
		else
		{
			pickspeed=80;
			flag=0;
		}
	}
	if(flag2)
	{
	if(c>200||c<20&&d>240)                     //red
  {
    flag=1;  }
  else if(c>160&&c<175&&d>235&&d<320)               //blue
	{
		flag=2;
  }
  else if(c<120&&c>80&&d>170&&d<240)                //green
  {
    flag=3;
  }
  else if(getMotorZeroPosition(switchMotor))
  {
    flag=0;
  }
  }
  motor[pickMotor1]=pickspeed;
	motor[pickMotor2]=pickspeed;

}

void switchcolor()
{
	  if(flag==1)
    {
    	e=0;
    }
    else if(flag==2)
    {
      e=120;
    }
    else if(flag==3)
    {
      e=240;
    }
    else if(vexRT[BtnEUp])
    {
    	e+=120;
    	while(vexRT[BtnEUp]){}
    }
    else if(vexRT[BtnEDown])
    {
    	e-=120;
    	while(vexRT[BtnEDown]){}
    }

    if(e>360)
    {
    	e=e-360;
    }
    if(e<-360)
    {
    	e=e+360;
    }
    setMotorTarget(switchMotor,e,100);
}

void remove()
{
	if(abs(vexRT[ChD])>15||abs(vexRT[ChB])>15)
	{
		motor[leftMotor]=vexRT[ChD]+vexRT[ChB];
		motor[rightMortor]=vexRT[ChD]-vexRT[ChB];
	}
	else
	{
		motor[leftMotor]=0;
		motor[rightMortor]=0;
	}
}

void ringarm()
{
	motor[armMotor]=vexRT[BtnLUp]*100-vexRT[BtnLDown]*100;
}


task main()
{
	while(1)
	{
		pick();
		switchcolor();
		ringarm();
		remove();
	}

}
